server:
  port: ${SERVICE_PORT:9003}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: admin
      database: admin
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9300

logging:
  level:
    org:
      springframework: DEBUG


security:
  oauth2:
    resource:
      id: accounting-rest-api
      jwt:
        key-value: signingKey

#axon:
#  eventhandling:
#    processors:
#      queryModel:
#        mode: tracking
#        source: eventBus
